name = "Newb X Lite"
version = [0, 1, 0]
min_supported_mc_version = [1, 26, 0]
description = '''
§c%w
§7- An enchanced vanilla shader for Minecraft! newb x legacy but stripped down even more with attempted better lighting
%v
§3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["Proxima"]
url = "https://github.com/Proxima101n/newb-x-lite"
uuid ="7d3f9a12-4b8c-4e21-93ad-6f1c2e874d50" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2026 %a

Fork of "Newb X Legacy" by devendrn (https://github.com/devendrn/newb-x-mcbe)
Original source licensed under MIT License.

This compiled pack is free to use. Source code available at https://github.com/Proxima101n/newb-x-lite under MIT License.

Contact: https://github.com/Proxima101n/newb-x-lite/issues
''' # %a = authors
credits = '''
Original shader by devendrn and Newb Shader Contributors
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Rounded Clouds
'''

[[subpack]]
define = "CHUNK_ANIM"
materials = ["RenderChunk"]
description = '''
Chunk loading animation
'''

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog and wave effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog effect
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''

[[subpack]]
define = "BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
Low + box clouds, looks better to me :)
'''

#[[subpack]]
#define = "Low"
#materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
#description = '''
#Many effects disabled. A bit lighter!
#'''